package Lexers;// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: C:/Users/kupc/IdeaProjects/TerminalColors/resources/colorscheme.flex

import Lexers.ColorType;
import Lexers.ColorsLexer;
import com.intellij.openapi.options.SchemeImportException;
import java.util.HashMap;
import java.util.Map;
import java.awt.*;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public
class ColorschemeColorsLexer implements ColorsLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COLORS = 2;
  public static final int READINGMODE = 4;
  public static final int GENERALMODE = 6;
  public static final int WRONGMODE = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4, 4
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\3\22\0\1\1"+
    "\13\0\1\4\1\0\1\5\1\0\1\6\1\7\1\10"+
    "\2\11\1\12\2\13\2\14\3\0\1\15\4\0\1\16"+
    "\1\17\1\20\1\0\1\21\1\22\1\0\1\23\5\0"+
    "\1\24\2\0\1\25\4\0\1\26\3\0\1\27\1\0"+
    "\1\30\3\0\1\31\1\0\1\32\1\33\1\34\1\0"+
    "\1\35\1\0\1\36\1\0\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\0\1\45\1\46\1\47\1\50\3\0"+
    "\1\51\1\52\u0185\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\2\1\1\2\4\0\1\3\4\4\1\0\2\1"+
    "\5\0\2\5\5\0\1\4\1\0\3\6\50\0\1\7"+
    "\1\1\10\0\1\10\14\0\1\11\33\0\3\6\2\0"+
    "\1\6\1\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\u0102\0\327"+
    "\0\u012d\0\u0158\0\u0183\0\u01ae\0\327\0\327\0\u01d9\0\u0204"+
    "\0\u022f\0\u025a\0\u0285\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c"+
    "\0\u0387\0\327\0\u03b2\0\u03dd\0\u0408\0\u0433\0\u045e\0\u0489"+
    "\0\u04b4\0\u04df\0\327\0\u050a\0\u0285\0\u0535\0\u0560\0\u058b"+
    "\0\u05b6\0\u05e1\0\u060c\0\u0637\0\u0662\0\u068d\0\u06b8\0\u06e3"+
    "\0\u070e\0\u0739\0\u0764\0\u078f\0\u07ba\0\u07e5\0\u0810\0\u083b"+
    "\0\u0866\0\u0891\0\u08bc\0\u08e7\0\u0912\0\u093d\0\u0968\0\u0993"+
    "\0\u09be\0\u09e9\0\u0a14\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0\0\u0aeb"+
    "\0\u0b16\0\u0b41\0\u0b6c\0\u0b97\0\u0bc2\0\327\0\u0a6a\0\u0bed"+
    "\0\u0c18\0\u0c43\0\u0c6e\0\u0c99\0\u0cc4\0\u0cef\0\u0d1a\0\327"+
    "\0\u0d45\0\u0d70\0\u0d9b\0\u0dc6\0\u0df1\0\u0e1c\0\u0e47\0\u0e72"+
    "\0\u0e9d\0\u0ec8\0\u0ef3\0\u0f1e\0\327\0\u0f49\0\u0f74\0\u0f9f"+
    "\0\u0fca\0\u0ff5\0\u1020\0\u104b\0\u1076\0\u10a1\0\u10cc\0\u10f7"+
    "\0\u1122\0\u114d\0\u1178\0\u11a3\0\u11ce\0\u11f9\0\u1224\0\u124f"+
    "\0\u127a\0\u12a5\0\u12d0\0\u12fb\0\u1326\0\u1351\0\u137c\0\u13a7"+
    "\0\u13d2\0\u13fd\0\u1428\0\u1453\0\u147e\0\u14a9\0\u14d4";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\3\6\1\7\23\6\1\10\23\6\1\0\2\6\1\7"+
    "\12\0\1\11\1\12\1\0\1\13\1\14\31\0\2\6"+
    "\1\7\1\15\1\0\1\16\1\17\1\20\4\21\2\0"+
    "\1\22\34\0\1\6\1\23\1\24\12\0\1\25\1\26"+
    "\1\27\3\0\1\30\1\0\1\31\25\0\2\32\1\33"+
    "\13\0\1\34\110\0\1\6\101\0\1\35\64\0\1\36"+
    "\52\0\1\37\43\0\1\40\24\0\7\21\44\0\4\21"+
    "\1\41\2\16\44\0\7\16\101\0\1\42\11\0\1\43"+
    "\1\44\51\0\1\45\1\44\107\0\1\46\55\0\1\47"+
    "\43\0\1\50\62\0\1\51\37\0\1\52\23\0\1\32"+
    "\113\0\1\53\41\0\1\54\60\0\1\55\57\0\1\56"+
    "\47\0\1\57\16\0\5\16\100\0\1\60\14\0\1\43"+
    "\120\0\1\61\42\0\1\62\60\0\1\63\35\0\1\64"+
    "\61\0\1\65\52\0\1\66\51\0\1\67\56\0\1\70"+
    "\43\0\1\67\52\0\1\71\61\0\1\72\54\0\1\73"+
    "\50\0\1\74\41\0\1\75\52\0\1\76\60\0\1\77"+
    "\55\0\1\100\44\0\1\101\62\0\1\102\52\0\1\103"+
    "\52\0\1\104\22\0\1\105\102\0\1\106\52\0\1\107"+
    "\43\0\1\110\60\0\1\111\53\0\1\112\52\0\1\113"+
    "\13\0\6\114\70\0\1\115\36\0\1\116\35\0\1\105"+
    "\1\117\1\6\1\7\47\105\25\0\1\120\63\0\1\121"+
    "\63\0\1\122\34\0\1\123\36\0\1\124\100\0\1\125"+
    "\30\0\1\126\1\0\1\127\4\0\1\130\62\0\1\131"+
    "\43\0\1\132\65\0\1\133\57\0\1\134\45\0\1\135"+
    "\14\0\1\136\1\137\1\140\4\141\106\0\1\142\33\0"+
    "\1\143\63\0\1\144\40\0\1\145\64\0\1\146\57\0"+
    "\1\147\20\0\1\150\71\0\1\61\22\0\1\151\52\0"+
    "\1\151\1\0\7\141\42\0\1\151\1\0\4\141\1\152"+
    "\2\136\42\0\1\151\1\0\7\136\100\0\1\153\46\0"+
    "\1\154\63\0\1\155\36\0\1\156\55\0\1\157\22\0"+
    "\1\160\1\161\51\0\1\162\1\163\1\164\4\165\42\0"+
    "\1\151\1\0\5\136\73\0\1\114\61\0\1\166\44\0"+
    "\1\167\61\0\1\170\52\0\1\171\11\0\1\6\1\7"+
    "\1\0\1\172\47\0\1\6\1\7\53\0\1\173\52\0"+
    "\1\173\1\0\7\165\42\0\1\173\1\0\4\165\1\174"+
    "\2\162\42\0\1\173\1\0\7\162\105\0\1\175\45\0"+
    "\1\176\51\0\1\177\53\0\1\73\16\0\7\200\44\0"+
    "\1\43\1\201\1\202\4\203\42\0\1\173\1\0\5\162"+
    "\70\0\1\130\70\0\1\204\42\0\1\205\16\0\1\6"+
    "\1\7\2\0\7\200\44\0\7\203\44\0\4\203\1\206"+
    "\2\43\44\0\7\43\72\0\1\175\70\0\1\207\6\0"+
    "\5\43\71\0\1\133\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5375];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\1\1\1\11\4\0\2\11\3\1\1\0"+
    "\2\1\5\0\1\11\1\1\5\0\1\1\1\0\1\11"+
    "\2\1\50\0\1\11\1\1\10\0\1\11\14\0\1\11"+
    "\33\0\3\1\2\0\1\1\1\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
private int generalCounter = 0;
private int red = -1;
private int green = -1;
private int blue = -1;
private int colorAmount = 0;
private String colorIdentifier;
private boolean decColorFound = false;
private boolean eqFound = false;
private Color color;
private static Map<String, String> nameMap;
static {
  nameMap = new HashMap<>();
  nameMap.put("Foreground]", ColorType.FOREGROUND);
  nameMap.put("Background]", ColorType.BACKGROUND);
  nameMap.put("Color0]", ColorType.ANSI[0]);
  nameMap.put("Color1]", ColorType.ANSI[1]);
  nameMap.put("Color2]", ColorType.ANSI[2]);
  nameMap.put("Color3]", ColorType.ANSI[3]);
  nameMap.put("Color4]", ColorType.ANSI[4]);
  nameMap.put("Color5]", ColorType.ANSI[5]);
  nameMap.put("Color6]", ColorType.ANSI[6]);
  nameMap.put("Color7]", ColorType.ANSI[7]);
  nameMap.put("Color0Intense]", ColorType.ANSI[8]);
  nameMap.put("Color1Intense]", ColorType.ANSI[9]);
  nameMap.put("Color2Intense]", ColorType.ANSI[10]);
  nameMap.put("Color3Intense]", ColorType.ANSI[11]);
  nameMap.put("Color4Intense]", ColorType.ANSI[12]);
  nameMap.put("Color5Intense]", ColorType.ANSI[13]);
  nameMap.put("Color6Intense]", ColorType.ANSI[14]);
  nameMap.put("Color7Intense]", ColorType.ANSI[15]);
}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ColorschemeColorsLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public ColorType yylex() throws java.io.IOException, SchemeImportException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              return null;
            }  // fall though
            case 136: break;
            case READINGMODE: {
              yybegin(YYINITIAL);
            }  // fall though
            case 137: break;
            case GENERALMODE: {
              yybegin(YYINITIAL);
            }  // fall though
            case 138: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /*ignore*/
            }
            // fall through
          case 10: break;
          case 2:
            { yybegin(COLORS);
            }
            // fall through
          case 11: break;
          case 3:
            { if (decColorFound && blue < 0) decColorFound = false;
                                        else throw new SchemeImportException("Scheme is not valid");
            }
            // fall through
          case 12: break;
          case 4:
            { if (eqFound) {
                                            if (!decColorFound)
                                            {if (red == -1) red = Integer.parseInt(yytext().toString());
                                            else if (green == -1) green = Integer.parseInt(yytext().toString());
                                            else if (blue == -1) blue = Integer.parseInt(yytext().toString());
                                            else throw new SchemeImportException("Scheme is not valid");
                                            if (red >= 0 && green >= 0 && blue >= 0) {
                                                color = new Color(red,green,blue);
                                                red = green = blue = -1;
                                                decColorFound = false;
                                                eqFound = false;
                                                yybegin(YYINITIAL);
                                                return new ColorType(colorIdentifier, color);
                                            }
                                            decColorFound = true;}
                                        else throw new SchemeImportException("Scheme is not valid");}
                                        else throw new SchemeImportException("Scheme is not valid");
            }
            // fall through
          case 13: break;
          case 5:
            { 
            }
            // fall through
          case 14: break;
          case 6:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 15: break;
          case 7:
            { eqFound = true;
            }
            // fall through
          case 16: break;
          case 8:
            { colorAmount++;
                                            if (nameMap.containsKey(yytext().toString())) {
                                            colorIdentifier = nameMap.get(yytext().toString());
                                            yybegin(READINGMODE);
                                            }
                                            else yybegin(WRONGMODE);
            }
            // fall through
          case 17: break;
          case 9:
            { yybegin(GENERALMODE);
            }
            // fall through
          case 18: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
